package com.example.tidus.ristrat.bean;

import java.io.Serializable;
import java.util.List;

public class Patient {


    /**
     * code : 0
     * message : 成功
     * server_params : {"willpush_list":[{"PATIENT_ID":"1678255","PATIENT_NAME":"唐天雨","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309963","PATIENT_TEL":"13811616239","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"极高危","BIRTHDAY":"29","CONFIRM_FLAG":20,"REPORT_ID":76,"RN":1,"MONITOR_NAME":""},{"PATIENT_ID":"1678253","PATIENT_NAME":"周智勇","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309963","PATIENT_TEL":"13811616239","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"极高危","BIRTHDAY":"19","CONFIRM_FLAG":20,"REPORT_ID":79,"RN":2,"MONITOR_NAME":""},{"PATIENT_ID":"1616235","PATIENT_NAME":"王宁宁","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309959","PATIENT_TEL":"13811616235","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"中危","BIRTHDAY":"44","CONFIRM_FLAG":20,"REPORT_ID":73,"RN":3,"MONITOR_NAME":""},{"PATIENT_ID":"1616236","PATIENT_NAME":"冯琪斌","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309960","PATIENT_TEL":"18513125685","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"极高危","BIRTHDAY":"36","CONFIRM_FLAG":10,"REPORT_ID":81,"RN":4,"MONITOR_NAME":""},{"PATIENT_ID":"1616237","PATIENT_NAME":"王超东","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309961","PATIENT_TEL":"13811616237","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"中危","BIRTHDAY":"40","CONFIRM_FLAG":10,"REPORT_ID":74,"RN":5,"MONITOR_NAME":""},{"PATIENT_ID":"1616243","PATIENT_NAME":"王小红","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309967","PATIENT_TEL":"13811616243","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"27","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":6,"MONITOR_NAME":""},{"PATIENT_ID":"1616244","PATIENT_NAME":"樊垚峰","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309968","PATIENT_TEL":"13811616244","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"51","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":7,"MONITOR_NAME":""},{"PATIENT_ID":"1616245","PATIENT_NAME":"曹利民","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309969","PATIENT_TEL":"13811616245","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"48","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":8,"MONITOR_NAME":""},{"PATIENT_ID":"1678254","PATIENT_NAME":"胡婷","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309963","PATIENT_TEL":"13811616239","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"39","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":9,"MONITOR_NAME":""},{"PATIENT_ID":"A1690904","PATIENT_NAME":"邴彦杉","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":10,"MONITOR_NAME":""},{"PATIENT_ID":"A1688426","PATIENT_NAME":"袁御","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":11,"MONITOR_NAME":""},{"PATIENT_ID":"A1684708","PATIENT_NAME":"宰嘉胜","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":12,"MONITOR_NAME":""},{"PATIENT_ID":"A1691271","PATIENT_NAME":"储欣德","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":13,"MONITOR_NAME":""},{"PATIENT_ID":"A1684762","PATIENT_NAME":"从鲲","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":14,"MONITOR_NAME":""},{"PATIENT_ID":"A1686297","PATIENT_NAME":"郗玲","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":15,"MONITOR_NAME":""},{"PATIENT_ID":"A1683255","PATIENT_NAME":"敖敬","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":16,"MONITOR_NAME":""},{"PATIENT_ID":"A1684059","PATIENT_NAME":"利勋","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":17,"MONITOR_NAME":""},{"PATIENT_ID":"A1692277","PATIENT_NAME":"雍嘉熙","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":18,"MONITOR_NAME":""},{"PATIENT_ID":"A1681228","PATIENT_NAME":"郑凡","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":19,"MONITOR_NAME":""},{"PATIENT_ID":"A1688112","PATIENT_NAME":"芮玉山","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":20,"MONITOR_NAME":""},{"PATIENT_ID":"A1683401","PATIENT_NAME":"那啸","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":21,"MONITOR_NAME":""},{"PATIENT_ID":"A1678521","PATIENT_NAME":"金俊英","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":22,"MONITOR_NAME":""},{"PATIENT_ID":"A1686514","PATIENT_NAME":"林良翰","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":23,"MONITOR_NAME":""},{"PATIENT_ID":"A1679991","PATIENT_NAME":"訾婉淑","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":24,"MONITOR_NAME":""},{"PATIENT_ID":"A1686229","PATIENT_NAME":"宁景焕","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":25,"MONITOR_NAME":""},{"PATIENT_ID":"A1681619","PATIENT_NAME":"浦绮波","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":26,"MONITOR_NAME":""},{"PATIENT_ID":"A1684217","PATIENT_NAME":"芮幻香","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":27,"MONITOR_NAME":""},{"PATIENT_ID":"A1686609","PATIENT_NAME":"寿梦桐","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":28,"MONITOR_NAME":""},{"PATIENT_ID":"A1683270","PATIENT_NAME":"慎康德","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":29,"MONITOR_NAME":""},{"PATIENT_ID":"A1691690","PATIENT_NAME":"濮瑶","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":30,"MONITOR_NAME":""},{"PATIENT_ID":"A1687613","PATIENT_NAME":"桂鹏运","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":31,"MONITOR_NAME":""},{"PATIENT_ID":"A1686900","PATIENT_NAME":"宓隽雅","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":32,"MONITOR_NAME":""},{"PATIENT_ID":"A1678401","PATIENT_NAME":"赵女","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":33,"MONITOR_NAME":""},{"PATIENT_ID":"A1682263","PATIENT_NAME":"池兴贤","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":34,"MONITOR_NAME":""},{"PATIENT_ID":"A1683275","PATIENT_NAME":"寿嘉泽","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":35,"MONITOR_NAME":""},{"PATIENT_ID":"A1688275","PATIENT_NAME":"慎鸿运","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":36,"MONITOR_NAME":""},{"PATIENT_ID":"A1683216","PATIENT_NAME":"衡斐","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":37,"MONITOR_NAME":""},{"PATIENT_ID":"A1689201","PATIENT_NAME":"丁泰和","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":38,"MONITOR_NAME":""},{"PATIENT_ID":"A1679669","PATIENT_NAME":"江蓓","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":39,"MONITOR_NAME":""},{"PATIENT_ID":"A1678335","PATIENT_NAME":"容佩玉","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":40,"MONITOR_NAME":""},{"PATIENT_ID":"A1686136","PATIENT_NAME":"越晓丝","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":41,"MONITOR_NAME":""},{"PATIENT_ID":"A1690489","PATIENT_NAME":"束娘","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":42,"MONITOR_NAME":""},{"PATIENT_ID":"A1683120","PATIENT_NAME":"暨映之","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":43,"MONITOR_NAME":""},{"PATIENT_ID":"A1688446","PATIENT_NAME":"邵英悟","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":44,"MONITOR_NAME":""},{"PATIENT_ID":"A1680498","PATIENT_NAME":"燕婷美","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":45,"MONITOR_NAME":""},{"PATIENT_ID":"A1682019","PATIENT_NAME":"燕易","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":46,"MONITOR_NAME":""},{"PATIENT_ID":"A1682635","PATIENT_NAME":"衡白山","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":47,"MONITOR_NAME":""},{"PATIENT_ID":"A1684851","PATIENT_NAME":"廖俊彦","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":48,"MONITOR_NAME":""},{"PATIENT_ID":"A1685670","PATIENT_NAME":"燕勤","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":49,"MONITOR_NAME":""},{"PATIENT_ID":"A1685835","PATIENT_NAME":"祖乐意","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":50,"MONITOR_NAME":""}],"LEVEL":[{"CURRENT_RISK_LEVEL":"6","RISK_NAME":"中危"},{"CURRENT_RISK_LEVEL":"8","RISK_NAME":"极高危"}],"willpush_count":14374,"MONITORSET":[{"MONITOR_ID":440,"MONITOR_NAME":"41-59岁下肢水肿患者","CREATE_TIME":"20190513135613","SERVICE_PLAN_ID":1002824,"MONITOR_LEVEL":null}]}
     * server_code :
     */

    private String code;
    private String message;
    private ServerParamsBean server_params;
    private String server_code;

    public String getCode() { return code;}

    public void setCode(String code) { this.code = code;}

    public String getMessage() { return message;}

    public void setMessage(String message) { this.message = message;}

    public ServerParamsBean getServer_params() { return server_params;}

    public void setServer_params(ServerParamsBean server_params) { this.server_params = server_params;}

    public String getServer_code() { return server_code;}

    public void setServer_code(String server_code) { this.server_code = server_code;}

    public static class ServerParamsBean {
        /**
         * willpush_list : [{"PATIENT_ID":"1678255","PATIENT_NAME":"唐天雨","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309963","PATIENT_TEL":"13811616239","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"极高危","BIRTHDAY":"29","CONFIRM_FLAG":20,"REPORT_ID":76,"RN":1,"MONITOR_NAME":""},{"PATIENT_ID":"1678253","PATIENT_NAME":"周智勇","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309963","PATIENT_TEL":"13811616239","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"极高危","BIRTHDAY":"19","CONFIRM_FLAG":20,"REPORT_ID":79,"RN":2,"MONITOR_NAME":""},{"PATIENT_ID":"1616235","PATIENT_NAME":"王宁宁","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309959","PATIENT_TEL":"13811616235","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"中危","BIRTHDAY":"44","CONFIRM_FLAG":20,"REPORT_ID":73,"RN":3,"MONITOR_NAME":""},{"PATIENT_ID":"1616236","PATIENT_NAME":"冯琪斌","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309960","PATIENT_TEL":"18513125685","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"极高危","BIRTHDAY":"36","CONFIRM_FLAG":10,"REPORT_ID":81,"RN":4,"MONITOR_NAME":""},{"PATIENT_ID":"1616237","PATIENT_NAME":"王超东","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309961","PATIENT_TEL":"13811616237","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":"30","PG":1,"RISK_NAME":"中危","BIRTHDAY":"40","CONFIRM_FLAG":10,"REPORT_ID":74,"RN":5,"MONITOR_NAME":""},{"PATIENT_ID":"1616243","PATIENT_NAME":"王小红","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309967","PATIENT_TEL":"13811616243","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"27","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":6,"MONITOR_NAME":""},{"PATIENT_ID":"1616244","PATIENT_NAME":"樊垚峰","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309968","PATIENT_TEL":"13811616244","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"51","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":7,"MONITOR_NAME":""},{"PATIENT_ID":"1616245","PATIENT_NAME":"曹利民","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309969","PATIENT_TEL":"13811616245","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"48","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":8,"MONITOR_NAME":""},{"PATIENT_ID":"1678254","PATIENT_NAME":"胡婷","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"000002309963","PATIENT_TEL":"13811616239","PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":0,"MARITAL_STATUS_CODE":"已婚","GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":"39","CONFIRM_FLAG":null,"REPORT_ID":null,"RN":9,"MONITOR_NAME":""},{"PATIENT_ID":"A1690904","PATIENT_NAME":"邴彦杉","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":10,"MONITOR_NAME":""},{"PATIENT_ID":"A1688426","PATIENT_NAME":"袁御","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":11,"MONITOR_NAME":""},{"PATIENT_ID":"A1684708","PATIENT_NAME":"宰嘉胜","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":12,"MONITOR_NAME":""},{"PATIENT_ID":"A1691271","PATIENT_NAME":"储欣德","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":13,"MONITOR_NAME":""},{"PATIENT_ID":"A1684762","PATIENT_NAME":"从鲲","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":14,"MONITOR_NAME":""},{"PATIENT_ID":"A1686297","PATIENT_NAME":"郗玲","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":15,"MONITOR_NAME":""},{"PATIENT_ID":"A1683255","PATIENT_NAME":"敖敬","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":16,"MONITOR_NAME":""},{"PATIENT_ID":"A1684059","PATIENT_NAME":"利勋","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":17,"MONITOR_NAME":""},{"PATIENT_ID":"A1692277","PATIENT_NAME":"雍嘉熙","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":18,"MONITOR_NAME":""},{"PATIENT_ID":"A1681228","PATIENT_NAME":"郑凡","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":19,"MONITOR_NAME":""},{"PATIENT_ID":"A1688112","PATIENT_NAME":"芮玉山","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":20,"MONITOR_NAME":""},{"PATIENT_ID":"A1683401","PATIENT_NAME":"那啸","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":21,"MONITOR_NAME":""},{"PATIENT_ID":"A1678521","PATIENT_NAME":"金俊英","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":22,"MONITOR_NAME":""},{"PATIENT_ID":"A1686514","PATIENT_NAME":"林良翰","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":23,"MONITOR_NAME":""},{"PATIENT_ID":"A1679991","PATIENT_NAME":"訾婉淑","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":24,"MONITOR_NAME":""},{"PATIENT_ID":"A1686229","PATIENT_NAME":"宁景焕","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":25,"MONITOR_NAME":""},{"PATIENT_ID":"A1681619","PATIENT_NAME":"浦绮波","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":26,"MONITOR_NAME":""},{"PATIENT_ID":"A1684217","PATIENT_NAME":"芮幻香","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":27,"MONITOR_NAME":""},{"PATIENT_ID":"A1686609","PATIENT_NAME":"寿梦桐","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":28,"MONITOR_NAME":""},{"PATIENT_ID":"A1683270","PATIENT_NAME":"慎康德","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":29,"MONITOR_NAME":""},{"PATIENT_ID":"A1691690","PATIENT_NAME":"濮瑶","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":30,"MONITOR_NAME":""},{"PATIENT_ID":"A1687613","PATIENT_NAME":"桂鹏运","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":31,"MONITOR_NAME":""},{"PATIENT_ID":"A1686900","PATIENT_NAME":"宓隽雅","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":32,"MONITOR_NAME":""},{"PATIENT_ID":"A1678401","PATIENT_NAME":"赵女","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":33,"MONITOR_NAME":""},{"PATIENT_ID":"A1682263","PATIENT_NAME":"池兴贤","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":34,"MONITOR_NAME":""},{"PATIENT_ID":"A1683275","PATIENT_NAME":"寿嘉泽","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":35,"MONITOR_NAME":""},{"PATIENT_ID":"A1688275","PATIENT_NAME":"慎鸿运","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":36,"MONITOR_NAME":""},{"PATIENT_ID":"A1683216","PATIENT_NAME":"衡斐","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":37,"MONITOR_NAME":""},{"PATIENT_ID":"A1689201","PATIENT_NAME":"丁泰和","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":38,"MONITOR_NAME":""},{"PATIENT_ID":"A1679669","PATIENT_NAME":"江蓓","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":39,"MONITOR_NAME":""},{"PATIENT_ID":"A1678335","PATIENT_NAME":"容佩玉","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":40,"MONITOR_NAME":""},{"PATIENT_ID":"A1686136","PATIENT_NAME":"越晓丝","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":41,"MONITOR_NAME":""},{"PATIENT_ID":"A1690489","PATIENT_NAME":"束娘","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":42,"MONITOR_NAME":""},{"PATIENT_ID":"A1683120","PATIENT_NAME":"暨映之","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":43,"MONITOR_NAME":""},{"PATIENT_ID":"A1688446","PATIENT_NAME":"邵英悟","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":44,"MONITOR_NAME":""},{"PATIENT_ID":"A1680498","PATIENT_NAME":"燕婷美","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":45,"MONITOR_NAME":""},{"PATIENT_ID":"A1682019","PATIENT_NAME":"燕易","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":46,"MONITOR_NAME":""},{"PATIENT_ID":"A1682635","PATIENT_NAME":"衡白山","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":47,"MONITOR_NAME":""},{"PATIENT_ID":"A1684851","PATIENT_NAME":"廖俊彦","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":48,"MONITOR_NAME":""},{"PATIENT_ID":"A1685670","PATIENT_NAME":"燕勤","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":49,"MONITOR_NAME":""},{"PATIENT_ID":"A1685835","PATIENT_NAME":"祖乐意","PATIENT_SEX":null,"MEDICAL_REC_NUMBER":null,"PATIENT_TEL":null,"PATIENT_NAME_PINYIN":null,"PATIENT_NAME_WUBI":null,"NOT_FOLLOW_UP":null,"MARITAL_STATUS_CODE":null,"GATHER_TYPE":null,"PG":1,"RISK_NAME":null,"BIRTHDAY":null,"CONFIRM_FLAG":null,"REPORT_ID":null,"RN":50,"MONITOR_NAME":""}]
         * LEVEL : [{"CURRENT_RISK_LEVEL":"6","RISK_NAME":"中危"},{"CURRENT_RISK_LEVEL":"8","RISK_NAME":"极高危"}]
         * willpush_count : 14374
         * MONITORSET : [{"MONITOR_ID":440,"MONITOR_NAME":"41-59岁下肢水肿患者","CREATE_TIME":"20190513135613","SERVICE_PLAN_ID":1002824,"MONITOR_LEVEL":null}]
         */

        private int willpush_count;
        private List<WillpushListBean> willpush_list;
        private List<LEVELBean> LEVEL;
        private List<MONITORSETBean> MONITORSET;

        public int getWillpush_count() { return willpush_count;}

        public void setWillpush_count(int willpush_count) { this.willpush_count = willpush_count;}

        public List<WillpushListBean> getWillpush_list() { return willpush_list;}

        public void setWillpush_list(List<WillpushListBean> willpush_list) { this.willpush_list = willpush_list;}

        public List<LEVELBean> getLEVEL() { return LEVEL;}

        public void setLEVEL(List<LEVELBean> LEVEL) { this.LEVEL = LEVEL;}

        public List<MONITORSETBean> getMONITORSET() { return MONITORSET;}

        public void setMONITORSET(List<MONITORSETBean> MONITORSET) { this.MONITORSET = MONITORSET;}

        public static class WillpushListBean implements Serializable{
            /**
             * PATIENT_ID : 1678255
             * PATIENT_NAME : 唐天雨
             * PATIENT_SEX : M
             * MEDICAL_REC_NUMBER : 000002309963
             * PATIENT_TEL : 13811616239
             * PATIENT_NAME_PINYIN : null
             * PATIENT_NAME_WUBI : null
             * NOT_FOLLOW_UP : 0
             * MARITAL_STATUS_CODE : 已婚
             * GATHER_TYPE : 30
             * PG : 1
             * RISK_NAME : 极高危
             * BIRTHDAY : 29
             * CONFIRM_FLAG : 20
             * REPORT_ID : 76
             * RN : 1
             * MONITOR_NAME :
             */

            private String PATIENT_ID;
            private String PATIENT_NAME;
            private String PATIENT_SEX;
            private String MEDICAL_REC_NUMBER;
            private String PATIENT_TEL;
            private Object PATIENT_NAME_PINYIN;
            private Object PATIENT_NAME_WUBI;
            private int NOT_FOLLOW_UP;
            private String MARITAL_STATUS_CODE;
            private String GATHER_TYPE;
            private int PG;
            private String RISK_NAME;
            private String BIRTHDAY;
            private int CONFIRM_FLAG;
            private int REPORT_ID;
            private int RN;
            private String MONITOR_NAME;

            public String getPATIENT_ID() { return PATIENT_ID;}

            public void setPATIENT_ID(String PATIENT_ID) { this.PATIENT_ID = PATIENT_ID;}

            public String getPATIENT_NAME() { return PATIENT_NAME;}

            public void setPATIENT_NAME(String PATIENT_NAME) { this.PATIENT_NAME = PATIENT_NAME;}

            public String getPATIENT_SEX() { return PATIENT_SEX;}

            public void setPATIENT_SEX(String PATIENT_SEX) { this.PATIENT_SEX = PATIENT_SEX;}

            public String getMEDICAL_REC_NUMBER() { return MEDICAL_REC_NUMBER;}

            public void setMEDICAL_REC_NUMBER(String MEDICAL_REC_NUMBER) { this.MEDICAL_REC_NUMBER = MEDICAL_REC_NUMBER;}

            public String getPATIENT_TEL() { return PATIENT_TEL;}

            public void setPATIENT_TEL(String PATIENT_TEL) { this.PATIENT_TEL = PATIENT_TEL;}

            public Object getPATIENT_NAME_PINYIN() { return PATIENT_NAME_PINYIN;}

            public void setPATIENT_NAME_PINYIN(Object PATIENT_NAME_PINYIN) { this.PATIENT_NAME_PINYIN = PATIENT_NAME_PINYIN;}

            public Object getPATIENT_NAME_WUBI() { return PATIENT_NAME_WUBI;}

            public void setPATIENT_NAME_WUBI(Object PATIENT_NAME_WUBI) { this.PATIENT_NAME_WUBI = PATIENT_NAME_WUBI;}

            public int getNOT_FOLLOW_UP() { return NOT_FOLLOW_UP;}

            public void setNOT_FOLLOW_UP(int NOT_FOLLOW_UP) { this.NOT_FOLLOW_UP = NOT_FOLLOW_UP;}

            public String getMARITAL_STATUS_CODE() { return MARITAL_STATUS_CODE;}

            public void setMARITAL_STATUS_CODE(String MARITAL_STATUS_CODE) { this.MARITAL_STATUS_CODE = MARITAL_STATUS_CODE;}

            public String getGATHER_TYPE() { return GATHER_TYPE;}

            public void setGATHER_TYPE(String GATHER_TYPE) { this.GATHER_TYPE = GATHER_TYPE;}

            public int getPG() { return PG;}

            public void setPG(int PG) { this.PG = PG;}

            public String getRISK_NAME() { return RISK_NAME;}

            public void setRISK_NAME(String RISK_NAME) { this.RISK_NAME = RISK_NAME;}

            public String getBIRTHDAY() { return BIRTHDAY;}

            public void setBIRTHDAY(String BIRTHDAY) { this.BIRTHDAY = BIRTHDAY;}

            public int getCONFIRM_FLAG() { return CONFIRM_FLAG;}

            public void setCONFIRM_FLAG(int CONFIRM_FLAG) { this.CONFIRM_FLAG = CONFIRM_FLAG;}

            public int getREPORT_ID() { return REPORT_ID;}

            public void setREPORT_ID(int REPORT_ID) { this.REPORT_ID = REPORT_ID;}

            public int getRN() { return RN;}

            public void setRN(int RN) { this.RN = RN;}

            public String getMONITOR_NAME() { return MONITOR_NAME;}

            public void setMONITOR_NAME(String MONITOR_NAME) { this.MONITOR_NAME = MONITOR_NAME;}
        }

        public static class LEVELBean {
            /**
             * CURRENT_RISK_LEVEL : 6
             * RISK_NAME : 中危
             */

            private String CURRENT_RISK_LEVEL;
            private String RISK_NAME;

            public String getCURRENT_RISK_LEVEL() { return CURRENT_RISK_LEVEL;}

            public void setCURRENT_RISK_LEVEL(String CURRENT_RISK_LEVEL) { this.CURRENT_RISK_LEVEL = CURRENT_RISK_LEVEL;}

            public String getRISK_NAME() { return RISK_NAME;}

            public void setRISK_NAME(String RISK_NAME) { this.RISK_NAME = RISK_NAME;}
        }

        public static class MONITORSETBean {
            /**
             * MONITOR_ID : 440
             * MONITOR_NAME : 41-59岁下肢水肿患者
             * CREATE_TIME : 20190513135613
             * SERVICE_PLAN_ID : 1002824
             * MONITOR_LEVEL : null
             */

            private int MONITOR_ID;
            private String MONITOR_NAME;
            private String CREATE_TIME;
            private int SERVICE_PLAN_ID;
            private Object MONITOR_LEVEL;

            public int getMONITOR_ID() { return MONITOR_ID;}

            public void setMONITOR_ID(int MONITOR_ID) { this.MONITOR_ID = MONITOR_ID;}

            public String getMONITOR_NAME() { return MONITOR_NAME;}

            public void setMONITOR_NAME(String MONITOR_NAME) { this.MONITOR_NAME = MONITOR_NAME;}

            public String getCREATE_TIME() { return CREATE_TIME;}

            public void setCREATE_TIME(String CREATE_TIME) { this.CREATE_TIME = CREATE_TIME;}

            public int getSERVICE_PLAN_ID() { return SERVICE_PLAN_ID;}

            public void setSERVICE_PLAN_ID(int SERVICE_PLAN_ID) { this.SERVICE_PLAN_ID = SERVICE_PLAN_ID;}

            public Object getMONITOR_LEVEL() { return MONITOR_LEVEL;}

            public void setMONITOR_LEVEL(Object MONITOR_LEVEL) { this.MONITOR_LEVEL = MONITOR_LEVEL;}
        }
    }
}
